### ISSUE TITLE
when init moveSimulator wilddog-location error

### ISSUE THREAD

**Issue by xiaopingyi** [WildDogTeam/demo-js-geomap#1]
![image](https://user-images.githubusercontent.com/19259376/30364773-2bc13bae-9898-11e7-8deb-c81d1720213a.png)

**Comment by dongkai1993** [comment]
wilddog-location@0.2.1 could not work well in node evn, please update to wilddog-location@0.2.2.
run `npm update wilddog-location` under 'moveSimulator/'.
Thanks for you issue!

**Comment by xiaopingyi** [comment]
Thank you! The problem haven been solved;
